### ISSUE TITLE
Split Repos Over Time and Size of Repos Over Time 

### ISSUE THREAD

**Issue by UriahShaulMandel** [cadekynaston/vuer#18]
Hi, I just saw your post on Reddit and I think it is a really cool project! thanks for open-sourcing it!
Just a small suggestion, IMO the `Repos Over Time Chart` and `Size of Repos Over Time Chart` should be split, because `Repos Over Time Chart`, the more important one IMO, becomes tiny.
![image](https://user-images.githubusercontent.com/43012268/72842171-81e62900-3ca0-11ea-8e2a-11e727e71474.png)
Thanks again for the project!

**Comment by cadekynaston** [comment]
Thank you! I agree and I originally had it that way but then I kept them combined in the end since you can toggle each data set. If you just want to see the number of Repos click the "Total size of repos" label and that data will be hidden.
